version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    volumes:
     - ./redis-data:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

  app:
    image: "shortlinks:latest"
    ports:
      - "5000:5000"
    environment:
      - DOMAIN=http://192.168.1.45/
      - REDIS_ADDR=redis:6379
      - REDIS_PW=sOmE_sEcUrE_pAsS
    networks:
      node_net:
        ipv4_address: 172.28.1.3
    links: 
      - redis
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./frontend/html:/usr/share/nginx/html:ro
      - ./frontend/nginx_conf:/etc/nginx:ro
    networks:
      node_net:
        ipv4_address: 172.28.1.2
    links:
      - app
    depends_on:
      - app

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16